apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: notes-webapp
spec:
  ports:
   - protocol: TCP
     port: 80   # service port 
     targetPort: 5173   # container port
     name: http
  type: ClusterIP
  selector:
    role: frontend
    app: frontend
