apiVersion: v1
kind: Service
metadata:
  namespace: wanderlust
  name: mongo
  labels:
    app: db
spec:
  clusterIP: None    # for Headless service it is "None"
  selector:
    app: db
  ports:
    - port: 27017
      targetPort: 27017