apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wanderlust
spec:
  ports:
    ptorocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
  selector:
    app: api
    tier: backend
    
  
