apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: wanderlust
  name: mongo
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        replicaset: rs0.main
    spec:
      containers:
      - name: mongo
        image: sohailshaikh23/wanderlust_mongo:4.4.6
        command:
          - "numactl"
          - "--interleave=all"
          - "mongod"
          - "--wiredTigerCacheSizeGB"
          - "0.1"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "rs0"
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
        volumeMounts:
          - name: mongo-persistent-storage-claim
            mountPath: /data/db  
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage-claim
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: 1Gi